### ISSUE TITLE
nginx issuing 301 redirects for no good reason

### ISSUE THREAD

**Issue by qrohlf** [vagrantpress/vagrantpress#56]
I'm trying to use [ngrok](https://ngrok.com) to tunnel my vagrantpress environment out so that my co-workers can view it remotely. I haven't changed anything in the vagrantfile, so port 8080 (host) is still being redirected to port 80 (guest). 

What I want to do on the host is tunnel port 8080 out with ngrok. I do this:

```
ngrok 8080
```

Which gives me a url like `http://37441ad7.ngrok.com` that is setup to forward port 80 on the ngrok server to port 8080 on my host machine (which should then be forwarded to port 80 on the vagrant VM). 

Unfortunately, the nginx port forwarding that Vagrant seems to use doesn't like this:

```
curl -I http://37441ad7.ngrok.com
HTTP/1.1 301 Moved Permanently
Server: nginx/1.4.5
Date: Fri, 14 Mar 2014 16:06:11 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
X-Powered-By: PHP/5.3.10-1ubuntu3.10
X-Pingback: http://localhost:8080/xmlrpc.php
Location: http://37441ad7.ngrok.com:8080/
Vary: Accept-Encoding
```

The resultant `http://37441ad7.ngrok.com:8080/` url doesn't work because the ngrok server is listening on port 80.

Any way that I could change the Vagrant config so that it doesn't redirect these requests that appear to be coming in from port 80?

**Comment by lafrance** [comment]
hello qrohlf  !

Thanks for the solutions it solved my problem too

**Comment by dustingtaylor** [comment]
Worked for me too! 👍

**Comment by JaosnHsieh** [comment]
it works for me !! thx

**Comment by Sakib37** [comment]
After almost 1 week I found the correct solution. Thanks a lot, @qrohlf

**Comment by lukaszkolasa** [comment]
So I did everything that you guys said, but I still cant get people to be able to access my wordpress project. When they click 'wordpress' in Your Projects they get redirected to a localhost adress instead of custom url provided by ngrok. I have relative URLs plugin installed. When I add the lines of code to wp-config it doesn't help at all. It even makes it worse by serving the page without any styling...

**Comment by LucidNinja** [comment]
Has anyone found a fix for this? I'm using Bedrock, Sage and Valet share (unsecured), and I just cannot get it to work. All my other sites work, but this is an older site that I have migrated across to Bedrock/Sage and Valet. Somehow it keeps redirecting to my .test/ domain on the home page, which means I get a "301 Moved Permanently" redirect in Terminal and trying to access the site remotely redirects to example.test/ instead of the ngrok domain. Note, accessing the ngrok URL with a subpage DOES work, but all of the assets are still served from the .test/ domain.
Recap:

- abcd.ngrok.io -> redirects to abcd.test/

- abcd.ngrok.io/about-us -> works but all assets are served from abcd.test/

- abcd.ngrok.io/wp-admin -> redirects to abcd.test/wp-admin

I am stumped!

Update: Sorry this is probably the wrong place to post this, but it was the closest I've come in Google searching...

**Comment by RobMaple** [comment]
@LucidNinja Not sure if you managed to get this working or not but I ran into the same issue and was able to work around it by sharing the site, then logging into the site via the .test URL and setting the permalink structure to 'plain, then editing the .env and setting the WP_HOME constant to the ngrok url.

**Comment by LucidNinja** [comment]
Amazing @RobMaple ! It's a weird workaround - but it works! Thank you! Be great if there was a way around this, to maintain the 'Post-Name' permalink structure. But that's the best workaround I've found so far! Thank you!
