### ISSUE TITLE
Multisite?

### ISSUE THREAD

**Issue by hllewelyn** [vagrantpress/vagrantpress#95]
I just tried following the multisite instructions in the [wiki](https://github.com/chad-thompson/vagrantpress/wiki/HOWTO:-WordPress-Multisite-in-VagrantPress), based on the original instructions on readme, and now the site is gone.

The only place I deviated  was the first instruction regarding forwarding the port, as that line wasn't in the vagrant press Vagrantfile any more. Is there an alternative for this?

**Comment by Johnstonian** [comment]
@Advocation, I tried this out and got it to work, with a couple caveats to the wiki. You don't have to change the port since the project moved to a hostname solution: http://vagrantpress.dev.

You can omit this step as well
```wp search-replace 'localhost:8080' 'localhost'```

Also, there is a slight typo with the section about editing the apache sites-enabled.

```sudo vi 000-default```

should be:

```sudo vi 000-default.conf```

And finally, point your browser to http://vagrantpress.dev/wp-admin/network/ to view the multisite admin area, not http://localhost/wp-admin/network/

Hope this helps...

**Comment by Johnstonian** [comment]
@Advocation, did my previous comment help you get multisite setup in vagrantpress?

**Comment by aluciu** [comment]
thank you for your clarifications.
everything was ok, i can see all the websites in dashboard. 
but when i access http://testing.vagrantpress.dev/ ... i get an error: "ERR_CONNECTION_TIMED_OUT", and the website is not loading.

**Comment by AngieB** [comment]
I'm encountering the same issue as aluciu, is there a known solution for this yet? 

Thanks!

**Comment by AngieB** [comment]
Nevermind, figured it out.  :) a new entry needed to be added to my host machine's /etc/hosts file for the new subdomain.

192.168.50.4  vagrantpress.dev  # VAGRANT: 00deed75b7959a2e1beb1e0d66cc7546 (default) / 5ca79fec-e65f-4b99-ac40-1e107117e00e
192.168.50.4  www.vagrantpress.dev  # VAGRANT: 00deed75b7959a2e1beb1e0d66cc7546 (default) / 5ca79fec-e65f-4b99-ac40-1e107117e00e
192.168.50.4 testing.vagrantpress.dev
